version: "3.3"
services:
    nginx:
        build:
            context: docker/nginx
        ports:
            - "8080:80"
        volumes:
            - .:/app
        links:
            - php-fpm
    php-fpm:
        build:
            context: docker/php-fpm
        volumes:
            - .:/app
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
        links:
            - mysql
            - redis
    mysql:
        image: mysql
        volumes:
            - ./db:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - "33061:3306"
    redis:
        image: redis
        ports:
            - "63791:6379"
    node:
        build:
            context: docker/node
        volumes:
            - .:/app
        tty: true
